name: Terraform CI

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    name: Terraform Validation and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: .
        run: terraform fmt -check -recursive infra

      - name: Disable Backend for CI
        run: mv backend.tf backend.tf.disabled

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Create CI tfvars
        env:
          DB_PASSWORD: ${{ secrets.TF_DB_PASSWORD }}
        run: |
          cat > ci.tfvars <<EOF
          aws_region   = "us-east-1"
          project_name = "devops-assignment-dev"
          vpc_cidr     = "10.0.0.0/16"

          db_name     = "appdb"
          db_username = "appuser"
          db_password = "$DB_PASSWORD"

          db_instance_class       = "db.t3.micro"
          backup_retention_period = 7
          deletion_protection     = false
          EOF

      - name: Terraform Plan
        run: terraform plan -var-file="ci.tfvars" -no-color